# Generated by Django 4.2.1 on 2023-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BandMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("instrument", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("image", models.ImageField(upload_to="band_members")),
            ],
        ),
        migrations.RemoveField(
            model_name="song",
            name="artist",
        ),
        migrations.DeleteModel(
            name="Concert",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
