# Generated by Django 4.2.1 on 2023-06-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0004_remove_album_cover_image_remove_bandmember_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Exclusive_content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="Concert",
            new_name="Concert_list",
        ),
        migrations.DeleteModel(
            name="BandMember",
        ),
        migrations.DeleteModel(
            name="ExclusiveEvent",
        ),
    ]
