# Generated by Django 4.2.1 on 2023-06-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0005_contact_exclusive_content_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert_list",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="exclusive_content",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
