# Generated by Django 4.2.1 on 2023-06-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0006_alter_concert_list_id_alter_exclusive_content_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exclusive_content",
            name="date",
        ),
        migrations.RemoveField(
            model_name="exclusive_content",
            name="location",
        ),
        migrations.RemoveField(
            model_name="exclusive_content",
            name="ticket_price",
        ),
        migrations.AlterField(
            model_name="concert_list",
            name="ticket_price",
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
