# Generated by Django 4.2.1 on 2023-07-23 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0008_alter_concert_list_id_alter_exclusive_content_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exclusive_content",
            old_name="description",
            new_name="list",
        ),
    ]
