# Generated by Django 4.2.1 on 2023-07-23 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0009_rename_description_exclusive_content_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exclusive_content",
            old_name="list",
            new_name="description",
        ),
    ]
