# Generated by Django 4.2.1 on 2023-07-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0010_rename_list_exclusive_content_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert_list",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
