# Generated by Django 4.2.1 on 2023-07-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0011_alter_concert_list_ticket_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExclusiveContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Exclusive_content",
        ),
    ]
